apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch-replicas.yaml

images:
  - name: order-service
    newName: 123456789012.dkr.ecr.us-east-1.amazonaws.com/dvop/order-service
    newTag: latest
